### ISSUE TITLE
Make a publisher class

### ISSUE THREAD

**Issue by LauraConnolly** [rosmed/slicer_ros2_module#11]

**Comment by adeguet1** [comment]
Publisher should check if there are subscribers before converting the data and sending anything (in `Publish` method).  If the number of subscribers is 0, return false.  Else, convert the message and actually call `publish` on `rclcpp::publisher`.  See similar logic: https://github.com/jhu-cisst/cisst_ros2_bridge/blob/6fb76b05348c72547300735ac8dc020a17194c91/include/cisst_ros2_bridge/mtsROSBridge.h#L88

Publisher should maintained two variables:
* `mNumberOfCalls`: incremented every time `Publish` is called
* `mNumberOfMessagesSent`: this assumes we only publish if the number of subscriber > 0,  it it is, mNumberOfMessagesSent += nb_subcribers.

**Comment by adeguet1** [comment]
For @aravindskumar98 , it seems we can create a `vtkSmartPointer` in Python. 
```python
>>> m = vtk.vtkMatrix4x4()
>>> p = vtk.vtkSmartPointerBase(m)
>>> p
vtkmodules.vtkCommonCore.vtkSmartPointerBase(0x55a52a96d110)
>>> p.GetPointer()
<vtkmodules.vtkCommonMath.vtkMatrix4x4(0x55a52a96d110) at 0x7f4561d39340>
>>> print(p.GetPointer())
vtkMatrix4x4 (0x55a52a96d110)
  Debug: Off
  Modified Time: 287938
  Reference Count: 2
  Registered Events: (none)
  Elements:
    1 0 0 0 
    0 1 0 0 
    0 0 1 0 
    0 0 0 1 
```
We might be able to publish using the smart pointer `p`.  I realize this is not very convenient so maybe we should overload the `Publish` method to support:
```c++
Publish(_slicer_type * input);
Publish(vtkSmartPointer<_slicer_type> input) { this->Publish(input->GetPointer()) };
```
The `vtkSlicerToROS2` methods for VTK data types should then be updated to use a plain pointer, e.g.:
```c++
vtkSlicerToROS2(vtkMatrix4x4 * input, geometry_msgs::msg::PoseStamped & output);
```

**Comment by aravindskumar98** [comment]
@adeguet1 Using `vtkSmartPointerBase` does not seem to help

`  File "<console>", line 1, in <module>
TypeError: PublishSmart argument 1: method requires a vtkSmartPointer_I12vtkMatrix4x4E, a vtkSmartPointerBase was provided.`

**Comment by aravindskumar98** [comment]
```py
ros2 = slicer.modules.ros2.logic()
pub = ros2.CreateAndAddPublisher('vtkMRMLROS2PublisherPoseStampedNode', 'pub_test')
  
# Create a 4x4 matrix
matrix = vtk.vtkMatrix4x4()

# Set the elements of the matrix
matrix.SetElement(0, 0, 0.707)
matrix.SetElement(0, 1, -0.707)
matrix.SetElement(0, 2, 0)
matrix.SetElement(0, 3, 0)
matrix.SetElement(1, 0, 0.707)
matrix.SetElement(1, 1, 0.707)
matrix.SetElement(1, 2, 0)
matrix.SetElement(1, 3, 0)
matrix.SetElement(2, 0, 0)
matrix.SetElement(2, 1, 0)
matrix.SetElement(2, 2, 1)
matrix.SetElement(2, 3, 0)
matrix.SetElement(3, 0, 0)
matrix.SetElement(3, 1, 0)
matrix.SetElement(3, 2, 0)
matrix.SetElement(3, 3, 1)
  
pub.Publish(matrix)
```

Command to create a custom matrix
