### ISSUE TITLE
how to save a node state and then restore

### ISSUE THREAD

**Issue by aravindskumar98** [rosmed/slicer_ros2_module#14]

**Comment by adeguet1** [comment]
In the latest implementation the NodeNode has multiple lists of references, i.e. "publisher", "subscriber" with NodeID of the publishers and subscribers attached to the ROS node.  We should probably add the reference Id of the ROS node to the subscriber and publisher.

**Comment by aravindskumar98** [comment]
Still open, but these were some interesting observations:

1. `/Slicer/Libs/MRML/Core/Testing/vtkMRMLSceneAddSingletonTest.cxx` seems to be testing the implementation of loading and saving. There is a .parse() for XML files
2. In the .mrml file, order of tags (from top to bottom) - ROS2Node  >  ROS2SubscriberString  >  ROS2SubscriberPoseStamped  >  ROS2SubscriberString  >  ROS2PublisherString  >  ROS2PublisherString
3. After overriding ReadXMLAttributes(), I added a simple print statement at the end of ReadXMLAttributes() to print out the type of Node being restored. And funnily, it prints it out in the exact same order as the MRML file. Even though the call to Superclass::ReadXMLAttributes() exists.

**Comment by aravindskumar98** [comment]
I kept digging longer for some way to access the scene. 

Function in vtkMRMLNode.h:

```cpp
  /// Updates other nodes in the scene depending on this node
  /// or updates this node if it depends on other nodes when the scene is read in
  /// This method is called automatically by XML parser after all nodes are created
  virtual void UpdateScene(vtkMRMLScene *)
  {
    this->UpdateNodeReferences();
  };
```

It seems to have access to the scene and is called after ReadXMLAttributes()

**Comment by aravindskumar98** [comment]
@adeguet1 publishers are active and <publisherNode>.Publish() is working. The same changes have been implemented for subscribers as well.

@LauraConnolly helped identify that the check for whether the publisher was previously referenced to the ROS node was interfering with the restore. It has been commented out for now. We were thinking of keeping an additional flag to bring back the  commented section.

**Comment by aravindskumar98** [comment]
Since `Create()` is called in `ROS2NODENode::ReadXMLAttributes()`, it always happens before `UpdateScene()` of any other node. Scrambling the _.mrml_ order does not do anything and it still works

**Comment by LauraConnolly** [comment]
I think that we might be able to check if reference is already added to the ROS2 MRML node and then if the pointer is set up on the ROS2 node separately. Right now they're updated together based on checking if the reference is there or not. For reloading this seemed to cause an issue because references are automatically restored but ros2 node pointers are not

**Comment by adeguet1** [comment]
Missing: make sure Logic knows about restored NODENode so it can spin it.  @adeguet1

**Comment by LauraConnolly** [comment]
@adeguet1 
Approaches: 

**onNodeAdded Research:** 
https://github.com/Slicer/Slicer/blob/a5f75351073ef62fd6198d9480d86c0009d70f9b/Modules/Loadable/Segmentations/qSlicerSegmentationsModule.cxx
- this module has the connection for OnNodeAdded on line 148 and the function onNodeAdded on line 222

or

**Get module logic in C++** 
- found example here: https://github.com/Slicer/Slicer/blob/a5f75351073ef62fd6198d9480d86c0009d70f9b/Modules/Loadable/Markups/MRMLDM/vtkMRMLMarkupsDisplayableManager.cxx
- see line 553

**Comment by adeguet1** [comment]
ROS node node is now added to vector in vtkLogic but it won't spin until we "open" the widget.  There might be a way to test if the widget is open and open it if it's not.
