### ISSUE TITLE
Move MRMLNodes files to a separate library

### ISSUE THREAD

**Issue by adeguet1** [rosmed/slicer_ros2_module#28]
@aravindskumar98 - I will work on this but if I recall correctly you had found an example for this.  Can you provide link?

**Comment by aravindskumar98** [comment]
@adeguet1 , this was the project I was referring to: https://github.com/SlicerIGT/SlicerIGT/tree/master/BreachWarning

I also this structure mentioned here: https://slicer.readthedocs.io/en/latest/developer_guide/mrml_overview.html#convention
