### ISSUE TITLE
Inconsistant ROS capitalization

### ISSUE THREAD

**Issue by adeguet1** [rosmed/slicer_ros2_module#33]
We currently use `ROS2` for the MRML nodes but we also have some `Ros2` in CMake for the module name and consequently for the Logic files.  I propose we change `Ros2` to `ROS2` everywhere.  Any objection? @LauraConnolly and @aravindskumar98 ?

**Comment by LauraConnolly** [comment]
That sounds good to me!

**Comment by aravindskumar98** [comment]
Alright with me!
