### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by adeguet1** [rosmed/slicer_ros2_module#44]
We could start with a simple python script but it would be good to create some tests, ideally both in C++ and Python.  For now, Python is likely more useful and would provide some indirect coverage for the C++ code.

**Comment by LauraConnolly** [comment]
https://github.com/LauraConnolly/OmniRobotIGT - example with python testing at the bottom (see OmniRobotIGT.py in OmniRobotIGT folder)

**Comment by aravindskumar98** [comment]
@adeguet1 this works. It's a quick fix : https://docs.python.org/3/library/runpy.html

```py
import runpy
runpy.run_path(<file_path>)
```

**Comment by LauraConnolly** [comment]
https://github.com/SlicerIGT/SlicerIGT/blob/master/LandmarkDetection/Testing/Cxx/CMakeLists.txt

**Comment by aravindskumar98** [comment]
Systematically execute custom python code on start-up

https://slicer.readthedocs.io/en/latest/user_guide/settings.html#application-startup-file

**Comment by aravindskumar98** [comment]
https://slicer.readthedocs.io/en/latest/developer_guide/python_faq.html#how-to-find-a-python-function-for-any-slicer-features

**Comment by aravindskumar98** [comment]
Starting widget from python terminal

```py
    >>> rosModule = slicer.modules.ros2
    >>> rosModule.logic().AddROS2Node()   # Creating the ROS2 Node
    >>> ros2Node = slicer.mrmlScene.GetFirstNodeByName('ros2:node:test_node')
    >>> testPub = ros2Node.CreateAndAddPublisher('vtkMRMLROS2PublisherStringNode', 'test_string_xkcd')
    >>> testSub = ros2Node.CreateAndAddSubscriber('vtkMRMLROS2SubscriberStringNode', 'test_string_xkcd')
    >>> testSub.GetLastMessageYAML() # Published message is not received

    'data: ""\n' 

    >>> rosModule.createNewWidgetRepresentation() # Creating a widget - does not show up on GUI though
    >>> testSub.GetLastMessageYAML()  # Published message is received by the Subscriber

    'data: "Test Publish"\n'
```

**Comment by aravindskumar98** [comment]
@adeguet1 I've modified the CMakeLists.txt to copy an additional .py file to `Slicer_DIR` 

This is saved in `Slicer_DIR` as .slicerrc.py and is _automatically run by 3D Slicer during startup_. It imports our unit tests library
