### ISSUE TITLE
Consolidate MRML files?

### ISSUE THREAD

**Issue by adeguet1** [rosmed/slicer_ros2_module#47]
Following the last commit (14bad6a), the number of files under MRML has significantly increased.  I propose to merge some of the files so it would be easier to navigate:
* `vtkMRMLROS2PublisherInternals.h` would contain all the publishers internal definitions, including `Native` and `VTK`
*  `vtkMRMLROS2PublisherMacross.h` would contain the `Native` and `VTK` macros
* `vtkMRMLROS2PublisherDefaultNodes.{h,cxx}` would contain both the Native and VTK instantiations
Overall, just for the publishers, the number of files would go from 11 to 6.

Thoughts?  @LauraConnolly and @aravindskumar98 ?

**Comment by aravindskumar98** [comment]
Sounds good!

**Comment by LauraConnolly** [comment]
Sounds good to me too!
